import { Certification } from "./types";

export const certifications: Certification[] = [
  // -------------------- RED TEAM --------------------
  {
    id: 1,
    slug: "ceh",
    title: "Certified Ethical Hacker",
    abbreviation: "CEH",
    description: "Learn ethical hacking fundamentals.",
    image: "/ceh.png",
    url: "https://eccouncil.org",
    cost: "$1199",
    training_included: true,
    number_of_attempts: 1,
    job_roles_titles: ["Penetration Tester", "Red Team"],
    cert_type: "red",
    total_votes: 320,
    market_presence: 0.82,
    cost_effectiveness: 3.8,
    skill_level: "Intermediate",
    quality: 4,
    satisfaction: 3.5,
    provider: {
      name: "EC-Council",
      url: "https://eccouncil.org",
      image: "/ec.png",
    },
    domains_covered_titles: ["Web", "Network"],
    requirements_data: {
      knowledge: "Basic security knowledge",
      work_experience: "0–1 years",
      prior_courses_and_certifications: "None",
    },
    exam_details_data: {
      format: "MCQ",
      duration: "4 hours",
      report_required: false,
    },
    valid_for: "3 years",
  },

  {
    id: 2,
    slug: "oscp",
    title: "Offensive Security Certified Professional",
    abbreviation: "OSCP",
    description: "Hands-on penetration testing certification.",
    image: "/oscp.png",
    url: "https://offsec.com",
    cost: "$1599",
    training_included: true,
    number_of_attempts: 1,
    job_roles_titles: ["PenTester", "Red Team Operator"],
    cert_type: "red",
    total_votes: 1400,
    market_presence: 0.96,
    cost_effectiveness: 4.8,
    skill_level: "Advanced",
    quality: 5,
    satisfaction: 4.9,
    provider: {
      name: "OffSec",
      url: "https://offsec.com",
      image: "/offsec.png",
    },
    domains_covered_titles: ["AD", "Web", "Network"],
    requirements_data: {
      knowledge: "Solid networking & Linux",
      work_experience: "1–2 years",
      prior_courses_and_certifications: "PWK",
    },
    exam_details_data: {
      format: "Practical Exam",
      duration: "24 hours",
      report_required: true,
    },
    valid_for: "4 years",
  },

  {
    id: 3,
    slug: "oswe",
    title: "Offensive Security Web Expert",
    abbreviation: "OSWE",
    description: "Advanced web exploitation certification.",
    image: "/oswe.png",
    url: "https://offsec.com",
    cost: "$1499",
    training_included: true,
    number_of_attempts: 1,
    job_roles_titles: ["Web App Pentester"],
    cert_type: "red",
    total_votes: 890,
    market_presence: 0.78,
    cost_effectiveness: 4.5,
    skill_level: "Advanced",
    quality: 5,
    satisfaction: 4.7,
    provider: {
      name: "OffSec",
      url: "https://offsec.com",
      image: "/offsec.png",
    },
    domains_covered_titles: ["Web", "API"],
    requirements_data: {
      knowledge: "Strong web development",
      work_experience: "2+ years",
      prior_courses_and_certifications: "OSCP recommended",
    },
    exam_details_data: {
      format: "Practical",
      duration: "48 hours",
      report_required: true,
    },
    valid_for: "4 years",
  },

  {
    id: 4,
    slug: "crto",
    title: "Certified Red Team Operator",
    abbreviation: "CRTO",
    description: "Realistic AD & red teaming labs.",
    image: "/crto.png",
    url: "https://zeropointsec.com",
    cost: "$399",
    training_included: true,
    number_of_attempts: 1,
    job_roles_titles: ["Red Teamer"],
    cert_type: "red",
    total_votes: 530,
    market_presence: 0.72,
    cost_effectiveness: 4.9,
    skill_level: "Intermediate",
    quality: 4.8,
    satisfaction: 4.6,
    provider: { name: "ZeroPoint Security", url: "", image: "/zps.png" },
    domains_covered_titles: ["AD", "Privilege Escalation"],
    requirements_data: {
      knowledge: "Windows + AD basics",
      work_experience: "1 year",
      prior_courses_and_certifications: "None",
    },
    exam_details_data: {
      format: "Hands-on",
      duration: "48 hours",
      report_required: false,
    },
    valid_for: "3 years",
  },

  // -------------------- BLUE TEAM --------------------

  {
    id: 5,
    slug: "sec_plus",
    title: "CompTIA Security+",
    abbreviation: "Sec+",
    description: "Entry-level security foundation.",
    image: "/secplus.png",
    url: "https://comptia.org",
    cost: "$499",
    training_included: false,
    number_of_attempts: 1,
    job_roles_titles: ["SOC Analyst", "Analyst I"],
    cert_type: "blue",
    total_votes: 2100,
    market_presence: 0.98,
    cost_effectiveness: 4.3,
    skill_level: "Beginner",
    quality: 4.1,
    satisfaction: 4.0,
    provider: { name: "CompTIA", url: "", image: "" },
    domains_covered_titles: ["Network", "Basics"],
    requirements_data: {
      knowledge: "Basic IT",
      work_experience: "0 years",
      prior_courses_and_certifications: "None",
    },
    exam_details_data: {
      format: "MCQ",
      duration: "90 minutes",
      report_required: false,
    },
    valid_for: "3 years",
  },

  {
    id: 6,
    slug: "cy_sa",
    title: "CompTIA Cybersecurity Analyst",
    abbreviation: "CySA+",
    description: "Blue team detection & response.",
    image: "/cysa.png",
    url: "https://comptia.org",
    cost: "$549",
    training_included: false,
    number_of_attempts: 1,
    job_roles_titles: ["SOC Analyst", "Incident Responder"],
    cert_type: "blue",
    total_votes: 760,
    market_presence: 0.76,
    cost_effectiveness: 4.0,
    skill_level: "Intermediate",
    quality: 4.2,
    satisfaction: 4.1,
    provider: { name: "CompTIA", url: "", image: "" },
    domains_covered_titles: ["Threat Detection", "Logs"],
    requirements_data: {
      knowledge: "Security+ recommended",
      work_experience: "1–2 years",
      prior_courses_and_certifications: "Security+",
    },
    exam_details_data: {
      format: "MCQ + Performance",
      duration: "165 minutes",
      report_required: false,
    },
    valid_for: "3 years",
  },

  {
    id: 7,
    slug: "gcia",
    title: "GIAC Intrusion Analyst",
    abbreviation: "GCIA",
    description: "Deep packet & intrusion analysis.",
    image: "/gcis.png",
    url: "https://giac.org",
    cost: "$2499",
    training_included: false,
    number_of_attempts: 1,
    job_roles_titles: ["SOC Lead"],
    cert_type: "blue",
    total_votes: 480,
    market_presence: 0.69,
    cost_effectiveness: 3.6,
    skill_level: "Advanced",
    quality: 4.7,
    satisfaction: 4.5,
    provider: { name: "GIAC", url: "", image: "" },
    domains_covered_titles: ["Network", "PCAP"],
    requirements_data: {
      knowledge: "Strong network analysis",
      work_experience: "2–3 years",
      prior_courses_and_certifications: "None",
    },
    exam_details_data: {
      format: "MCQ",
      duration: "4 hours",
      report_required: false,
    },
    valid_for: "4 years",
  },

  {
    id: 8,
    slug: "blue_team_level1",
    title: "Blue Team Level 1",
    abbreviation: "BTL1",
    description: "Hands-on defensive security.",
    image: "/btl1.png",
    url: "https://bluetamhq.com",
    cost: "$399",
    training_included: true,
    number_of_attempts: 1,
    job_roles_titles: ["SOC Analyst"],
    cert_type: "blue",
    total_votes: 560,
    market_presence: 0.71,
    cost_effectiveness: 4.7,
    skill_level: "Beginner",
    quality: 4.8,
    satisfaction: 4.7,
    provider: { name: "Blue Team HQ", url: "", image: "" },
    domains_covered_titles: ["SIEM", "Logs", "Network"],
    requirements_data: {
      knowledge: "Basic security",
      work_experience: "0–1 year",
      prior_courses_and_certifications: "None",
    },
    exam_details_data: {
      format: "Practical",
      duration: "24 hours",
      report_required: false,
    },
    valid_for: "3 years",
  },

  // -------------------- INFOSEC CERTIFICATIONS --------------------

  {
    id: 9,
    slug: "cissp",
    title: "Certified Information Systems Security Professional",
    abbreviation: "CISSP",
    description: "Industry-leading security management cert.",
    image: "/cissp.png",
    url: "https://isc2.org",
    cost: "$749",
    training_included: false,
    number_of_attempts: 1,
    job_roles_titles: ["Security Manager", "Architect"],
    cert_type: "infoSec",
    total_votes: 2400,
    market_presence: 0.99,
    cost_effectiveness: 4.4,
    skill_level: "Expert",
    quality: 5,
    satisfaction: 4.6,
    provider: { name: "ISC2", url: "", image: "" },
    domains_covered_titles: ["IAM", "Security Program"],
    requirements_data: {
      knowledge: "Security management",
      work_experience: "5 years",
      prior_courses_and_certifications: "Any ISC2",
    },
    exam_details_data: {
      format: "CAT",
      duration: "4 hours",
      report_required: false,
    },
    valid_for: "3 years",
  },

  {
    id: 10,
    slug: "cism",
    title: "Certified Information Security Manager",
    abbreviation: "CISM",
    description: "Security governance and risk management.",
    image: "/cism.png",
    url: "https://isaca.org",
    cost: "$760",
    training_included: false,
    number_of_attempts: 1,
    job_roles_titles: ["Security Manager"],
    cert_type: "infoSec",
    total_votes: 1700,
    market_presence: 0.93,
    cost_effectiveness: 4.2,
    skill_level: "Expert",
    quality: 4.6,
    satisfaction: 4.4,
    provider: { name: "ISACA", url: "", image: "" },
    domains_covered_titles: ["Governance"],
    requirements_data: {
      knowledge: "Security mgmt",
      work_experience: "5 years",
      prior_courses_and_certifications: "None",
    },
    exam_details_data: {
      format: "MCQ",
      duration: "4 hours",
      report_required: false,
    },
    valid_for: "3 years",
  },

  {
    id: 11,
    slug: "iso_27001",
    title: "ISO 27001 Lead Implementer",
    abbreviation: "ISO27001-LI",
    description: "Information security management system.",
    image: "/iso.png",
    url: "https://pecb.com",
    cost: "$1299",
    training_included: true,
    number_of_attempts: 1,
    job_roles_titles: ["Compliance", "Auditor"],
    cert_type: "infoSec",
    total_votes: 640,
    market_presence: 0.68,
    cost_effectiveness: 3.9,
    skill_level: "Intermediate",
    quality: 4.3,
    satisfaction: 4.2,
    provider: { name: "PECB", url: "", image: "" },
    domains_covered_titles: ["GRC"],
    requirements_data: {
      knowledge: "ISO basics",
      work_experience: "1–3 years",
      prior_courses_and_certifications: "None",
    },
    exam_details_data: {
      format: "MCQ",
      duration: "3 hours",
      report_required: true,
    },
    valid_for: "3 years",
  },

  {
    id: 12,
    slug: "risk_it",
    title: "CRISC — Risk and Information Systems Control",
    abbreviation: "CRISC",
    description: "Enterprise-level risk management.",
    image: "/crisc.png",
    url: "https://isaca.org",
    cost: "$760",
    training_included: false,
    number_of_attempts: 1,
    job_roles_titles: ["Risk Analyst"],
    cert_type: "infoSec",
    total_votes: 430,
    market_presence: 0.54,
    cost_effectiveness: 4.0,
    skill_level: "Advanced",
    quality: 4.5,
    satisfaction: 4.3,
    provider: { name: "ISACA", url: "", image: "" },
    domains_covered_titles: ["Risk"],
    requirements_data: {
      knowledge: "Risk fundamentals",
      work_experience: "3+ years",
      prior_courses_and_certifications: "None",
    },
    exam_details_data: {
      format: "MCQ",
      duration: "4 hours",
      report_required: false,
    },
    valid_for: "3 years",
  },

  // ------------------- MORE DATA (for better charts) -------------------
  {
    id: 13,
    slug: "pentestplus",
    title: "CompTIA PenTest+",
    abbreviation: "PT+",
    description: "Intermediate penetration testing.",
    image: "",
    url: "",
    cost: "$449",
    training_included: false,
    number_of_attempts: 1,
    job_roles_titles: ["Pentester"],
    cert_type: "red",
    total_votes: 900,
    market_presence: 0.83,
    cost_effectiveness: 4.1,
    skill_level: "Intermediate",
    quality: 4.0,
    satisfaction: 3.9,
    provider: null,
    domains_covered_titles: ["Network", "Web"],
    requirements_data: {
      knowledge: "Security+ recommended",
      work_experience: "1 year",
      prior_courses_and_certifications: "Security+",
    },
    exam_details_data: {
      format: "MCQ + Performance",
      duration: "165 minutes",
      report_required: false,
    },
    valid_for: "3 years",
  },

  {
    id: 14,
    slug: "gpen",
    title: "GIAC Penetration Tester",
    abbreviation: "GPEN",
    description: "Advanced penetration testing course.",
    image: "",
    url: "",
    cost: "$2499",
    training_included: false,
    number_of_attempts: 1,
    job_roles_titles: ["Pentester"],
    cert_type: "red",
    total_votes: 580,
    market_presence: 0.59,
    cost_effectiveness: 3.7,
    skill_level: "Advanced",
    quality: 4.8,
    satisfaction: 4.6,
    provider: null,
    domains_covered_titles: ["Network", "Web"],
    requirements_data: {
      knowledge: "Intermediate pentesting",
      work_experience: "2 years",
      prior_courses_and_certifications: "None",
    },
    exam_details_data: {
      format: "MCQ",
      duration: "4 hours",
      report_required: false,
    },
    valid_for: "4 years",
  },

  {
    id: 15,
    slug: "gsec",
    title: "GIAC Security Essentials",
    abbreviation: "GSEC",
    description: "General cybersecurity fundamentals.",
    image: "",
    url: "",
    cost: "$2499",
    training_included: false,
    number_of_attempts: 1,
    job_roles_titles: ["Security Analyst"],
    cert_type: "infoSec",
    total_votes: 1250,
    market_presence: 0.86,
    cost_effectiveness: 4.0,
    skill_level: "Intermediate",
    quality: 4.5,
    satisfaction: 4.4,
    provider: null,
    domains_covered_titles: ["Network", "IAM"],
    requirements_data: {
      knowledge: "IT basics",
      work_experience: "0–1 years",
      prior_courses_and_certifications: "None",
    },
    exam_details_data: {
      format: "MCQ",
      duration: "4 hours",
      report_required: false,
    },
    valid_for: "4 years",
  },

  {
    id: 16,
    slug: "ccna_security",
    title: "Cisco CCNA Security",
    abbreviation: "CCNA-S",
    description: "Cisco network security foundations.",
    image: "",
    url: "",
    cost: "$399",
    training_included: false,
    number_of_attempts: 1,
    job_roles_titles: ["Network Security"],
    cert_type: "blue",
    total_votes: 1100,
    market_presence: 0.88,
    cost_effectiveness: 4.2,
    skill_level: "Beginner",
    quality: 4.0,
    satisfaction: 3.8,
    provider: null,
    domains_covered_titles: ["Network"],
    requirements_data: {
      knowledge: "CCNA recommended",
      work_experience: "0 years",
      prior_courses_and_certifications: "CCNA",
    },
    exam_details_data: {
      format: "MCQ",
      duration: "120 minutes",
      report_required: false,
    },
    valid_for: "3 years",
  },

  {
    id: 17,
    slug: "ccsk",
    title: "Certificate of Cloud Security Knowledge",
    abbreviation: "CCSK",
    description: "Cloud security fundamentals.",
    image: "",
    url: "",
    cost: "$395",
    training_included: false,
    number_of_attempts: 1,
    job_roles_titles: ["Cloud Security"],
    cert_type: "infoSec",
    total_votes: 560,
    market_presence: 0.62,
    cost_effectiveness: 4.3,
    skill_level: "Intermediate",
    quality: 4.1,
    satisfaction: 4.0,
    provider: null,
    domains_covered_titles: ["Cloud"],
    requirements_data: {
      knowledge: "IT basics",
      work_experience: "1 year",
      prior_courses_and_certifications: "None",
    },
    exam_details_data: {
      format: "MCQ",
      duration: "90 minutes",
      report_required: false,
    },
    valid_for: "2 years",
  },

  {
    id: 18,
    slug: "ccsp",
    title: "Certified Cloud Security Professional",
    abbreviation: "CCSP",
    description: "Advanced cloud security.",
    image: "",
    url: "",
    cost: "$749",
    training_included: false,
    number_of_attempts: 1,
    job_roles_titles: ["Cloud Architect"],
    cert_type: "infoSec",
    total_votes: 940,
    market_presence: 0.78,
    cost_effectiveness: 4.0,
    skill_level: "Advanced",
    quality: 4.8,
    satisfaction: 4.6,
    provider: null,
    domains_covered_titles: ["Cloud"],
    requirements_data: {
      knowledge: "Cloud concepts",
      work_experience: "3 years",
      prior_courses_and_certifications: "CCSK recommended",
    },
    exam_details_data: {
      format: "MCQ",
      duration: "4 hours",
      report_required: false,
    },
    valid_for: "3 years",
  },

  {
    id: 19,
    slug: "azure_sc_900",
    title: "Microsoft Security Fundamentals",
    abbreviation: "SC-900",
    description: "Intro to Microsoft cloud security.",
    image: "",
    url: "",
    cost: "$99",
    training_included: false,
    number_of_attempts: 1,
    job_roles_titles: ["Cloud Analyst"],
    cert_type: "blue",
    total_votes: 900,
    market_presence: 0.74,
    cost_effectiveness: 4.8,
    skill_level: "Novice",
    quality: 4.2,
    satisfaction: 4.1,
    provider: null,
    domains_covered_titles: ["Cloud"],
    requirements_data: {
      knowledge: "Basic cloud",
      work_experience: "0 years",
      prior_courses_and_certifications: "None",
    },
    exam_details_data: {
      format: "MCQ",
      duration: "45 minutes",
      report_required: false,
    },
    valid_for: "Lifetime",
  },

  {
    id: 20,
    slug: "azure_sc_200",
    title: "Microsoft Security Operations Analyst",
    abbreviation: "SC-200",
    description: "Blue team cloud detection & response.",
    image: "",
    url: "",
    cost: "$165",
    training_included: false,
    number_of_attempts: 1,
    job_roles_titles: ["Cloud SOC Analyst"],
    cert_type: "blue",
    total_votes: 680,
    market_presence: 0.66,
    cost_effectiveness: 4.5,
    skill_level: "Intermediate",
    quality: 4.3,
    satisfaction: 4.2,
    provider: null,
    domains_covered_titles: ["Cloud", "SIEM"],
    requirements_data: {
      knowledge: "Cloud + SIEM",
      work_experience: "1 year",
      prior_courses_and_certifications: "SC-900 recommended",
    },
    exam_details_data: {
      format: "MCQ",
      duration: "120 minutes",
      report_required: false,
    },
    valid_for: "1 year",
  },

  {
    id: 21,
    slug: "for_508",
    title: "GIAC Forensics Analyst",
    abbreviation: "GCFA",
    description: "Digital forensics certification.",
    image: "",
    url: "",
    cost: "$2499",
    training_included: false,
    number_of_attempts: 1,
    job_roles_titles: ["Forensics Analyst"],
    cert_type: "blue",
    total_votes: 480,
    market_presence: 0.58,
    cost_effectiveness: 3.8,
    skill_level: "Advanced",
    quality: 4.6,
    satisfaction: 4.4,
    provider: null,
    domains_covered_titles: ["Forensics"],
    requirements_data: {
      knowledge: "Windows + Linux",
      work_experience: "1–3 years",
      prior_courses_and_certifications: "None",
    },
    exam_details_data: {
      format: "MCQ",
      duration: "4 hours",
      report_required: false,
    },
    valid_for: "4 years",
  },
];
